#!/bin/bash

# backup tool for $HOME/docs directory
# matches the date of creation against marker file

thedate="`date +%F_%H-%M-%S`"
outfile="$HOME/backup/tape/docs-$thedate.cpio"

flist="`find $HOME/docs -cnewer $HOME/.marker -print`"
if [ -z "$flist" ] ; then
    echo "There's nothing new to backup"
    exit 0
fi

echo "Backing up $HOME/docs to $outfile"

echo "$flist" | cpio -oO $outfile
touch $HOME/.marker

echo "Compressing ..."
gzip $outfile

echo "Done!"

exit 0
