#!/bin/bash

function modification {
 sed -s "s/.jpg/_thumb.jpg/"
 sed -s "s/.png/_thumb.png/"
}

if [ $# -eq 0 ] ; then
  res="300"
else
  res="$1"
fi

for photo in *.jpg *.png; do 
 convert -resize "$res" "$photo" "$( echo ${photo} | modification )"
done

