#!/usr/bin/env bash


# usage notification
if [ $# -eq 0 ] ; then
 cat <<EOF >&2
 Usage: $0 \"URL\"
EOF
 exit 1
else 
 site="$1"
fi

# helper function -- get base url of the site
function base_url {
 echo "$site" | sed -r 's@.*//([^ /]+).*@\1@g'
}

# get the website
wget \
     --recursive \
     --no-clobber \
     --page-requisites \
     --html-extension \
     --convert-links \
     --restrict-file-names=windows \
     --domains $( base_url ) \
     --no-parent \
         "$site"

exit 0
