#!/bin/bash

##################################################################
# sitemap -- generates sitemap into standard output
#
# Usage: $0 \"URL\" [frequency] [priority]
# where 
# [frequency]: always, hourly,daily, [monthly], yearly, never 
# [priority]: ranges from 0.0 to 1.0. 
# Priority equals [0.5] is default
##################################################################

function on_exit {
 rm -f traverse.dat traverse2.dat traverse.errors reject.dat traverse.$$
}

trap "on_exit" EXIT

# usage notification
if [ $# -eq 0 ] ; then
 cat <<EOF >&2
 Usage: $0 \"URL\" [frequency] [priority]
 where [frequency]: always, hourly,daily, [monthly], yearly, never
 [priority]: ranges from 0.0 to 1.0. Priority equals [0.5] is default
EOF

 exit 1
else 
 site="$1"
 freq="$2"
 pri="$3"
 lastmod="$( date -u +%Y-%m-%d )"
fi

if [ -z "$2" ] ; then
 freq="monthly"
fi

if [ -z "$3" ] ; then
 pri="0.5"
fi

# getting site URLs
lynx -traversal -accept_all_cookies "$site" > /dev/null

# header
cat <<EOF 
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
EOF

# utf8 encoding
cat traverse.dat | sed -s "s/&/&amp;/g" > traverse.$$

for url in $( cat traverse.$$ ) ; do
 cat <<EOF 
  <url>
    <loc>$url</loc>
    <lastmod>$lastmod</lastmod>
    <changefreq>$freq</changefreq>
    <priority>$pri</priority>
  </url>
EOF

done

cat <<EOF 
</urlset>
EOF

exit 0
