#!/usr/bin/env bash

##################################################################
# snapshot -- creates an archive of the specified directory.
#
# Usage: snapshot [directory] 
#
# When [directory] is omitted, creates an archive
# of the current directory.
##################################################################

snapdir="/mnt/data/backup/snapshots"
thedate="$( date +%F_%H-%M-%S )"
script_name="$( basename $0 )"

if [ $# -gt 0 ] ; then
    if [ -d "$1" ] ; then
	dirs="$( echo $1 | sed -s "s/\/$//" )"
	outfile="${snapdir}/${dirs}-${thedate}.tar.gz"
    else 
	echo "${script_name}: cannot access ${1}. No such directory"
	exit 1
    fi
else
    dirs="."
    thename="$( basename $( pwd ) )"
    outfile="${snapdir}/${thename}-${thedate}.tar.gz"
fi

echo "Creating an archive of ${dirs} as ${outfile}..."

tar -czvf $outfile $dirs

echo "Done!"

exit 0
