#!/bin/bash

# renames files in local directory, removing whitespaces, changing upper
# cases to lower cases and transliterating cyrillic into latin

# IFS="\n"


if [ -n "$1" ] ; then
    dir="$( echo $1 | sed -r 's/\/$//' )"
else
    dir="."
fi

function translit {
    sed -s "s/.*/\L&/; s/ /_/g; s/(//g; s/)//g; s/?//g; s/ь//g; s/ъ/y/; " | 
    sed -r "y/\(а|б|в|г|д|е|з|и|к|л|м|н|о|п|р|с|т|у|ф\)/\(a|b|v|g|d|e|z|i|k|l|m|n|o|p|r|s|t|u|f\)/" |
    sed -s "s/ж/zh/g; s/й/yo/g; s/х/kh/g; s/ц/ts/g; s/ч/ch/g; s/ш/sh/g; s/щ/sch/g; s/ы/y/g; s/ю/yu/g; s/я/ya/g"
}

for file in ${dir}/* ; do
    mv "$file" "$( echo ${file} | translit )" ;
done
# exit 0
